### ISSUE TITLE
Could you add .zip/.7z or even .tar.xz for the first release?

### ISSUE THREAD

**Issue by dsalychev** [AbdullrahmanAlzeidi/Ainan#4]
Well, subject.

I wouldn't try to install anything to unpack .rar because it's a _proprietary_ format [1]. There is no need to use it, I guess. Could you provide an alternative?

Thanks.

[1] https://en.wikipedia.org/wiki/RAR_(file_format)

**Comment by Abdul-AZ** [comment]
Thanks for the suggestion :)

Adding them now!

**Comment by dsalychev** [comment]
OK, I'll close issue then. No problem ;)
